### ISSUE TITLE
Use a dedicated exception for the check added in #10785

### ISSUE THREAD

**Issue by mpdude** [doctrine/doctrine2#10872]
... to follow up on https://github.com/doctrine/orm/pull/10785#issuecomment-1663606294.

**Comment by gbirke** [comment]
I'm very much looking forward to this :smile: 
I suggest creating the exception in the `Doctrine\ORM` namespace and not reusing the one from DBAL, because in other places of the code (i.e. `flush`), @Ocramius mentioned he doesn't like the underlying layer bleeding into the ORM layer, see https://github.com/doctrine/orm/issues/7780#issuecomment-517436821

**Comment by mpdude** [comment]
Implemented in #10881
