### ISSUE TITLE
Schema validator should check that typed PHP properties is compatible with database type

### ISSUE THREAD

**Issue by bastnic** [doctrine/doctrine2#10944]
### Feature Request

I have a decimal wrongly mapped to a float. [The doc](https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/types.html#decimal) seems to say that it should be a string but the devs miss that notice.

```php
#[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 6, nullable: true)]
private ?float $latitude = null;
```

We experienced no functional bug, the data is correctly passed everywhere and no data loss. 

But one day I notice that this table is udpated a LOT without logical reason. 

basic code was 

```php

$order = $this->orderRepository->find($orderId);

$stuff->setFedexTracking($order->getFedexTracking());

$this->entityManager->flush();
```

here `$order` is readonly but the table is updated anyway, maybe because of the cast from string to float.

Maybe the Schema validator should check that `$latitude` must be a string? 

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | yes

#### Summary

Not sur that it is really a thing but I wanted to write it somewhere that can be found by someone that need it.

That is a NICE optim for just a conversion of one variable from float to string
![image](https://github.com/doctrine/orm/assets/84887/7553d8a0-d8e1-46c5-92f5-fe81704ceeec)

**Comment by greg0ire** [comment]
My reaction when hearing about this was that we should probably check this on schema validation, but after taking a closer look, there is no formal declaration of the php type in a DBAL type. In `DecimalType`, you will just see a comment mentioning "Type that maps an SQL DECIMAL to a PHP string.". So maybe the next best thing would be a crash at runtime, when attempting to hydrate a property with another type. That being said, that is something `strict_types` forbids natively: https://3v4l.org/XNgtq

**Comment by derrabus** [comment]
> That being said, that is something `strict_types` forbids natively: https://3v4l.org/XNgtq

👀 https://3v4l.org/A9Q5u

**Comment by derrabus** [comment]
I believe that this is a good idea. Decimals especially are a common pitfall. Do you want to implement that feature?

**Comment by greg0ire** [comment]
Thanks @derrabus ! What you describe is done here according to the reproducer I made: https://github.com/doctrine/orm/blob/858b01f85ed4852e1c3f13016179d31e9e5f09e1/lib/Doctrine/ORM/UnitOfWork.php#L2921-L2925

It's possible to obtain the type of the property with `$class->reflFields[$field]->getType()->getName()`. It could be compared with `gettype($value)`, although that will not be a very straightforward comparison I'm afraid: that function has return values that don't always match their counterparts from the reflection API.

> Do you want to implement that feature?

I think I might :)


> I believe that this is a good idea

After more thinking, I'm not sure it would actually be a great idea, because this might slow down hydration :thinking: 

>  there is no formal declaration of the php type in a DBAL type

That's no longer true with DBAL 4. I think we should wait for this, that way we can do this on schema validation.

**Comment by derrabus** [comment]
If you want runtime errors, we could consider using closure binding instead of reflection to set properties. That should give us a fine `TypeError` if strict types are enabled.

But I think, I'd prefer to make the schema validator complain about incompatible types first.

**Comment by OskarStark** [comment]
What about at least a PHPStan rule to point this out?

cc @staabm

**Comment by bastnic** [comment]
hmm, duplicate of https://github.com/doctrine/orm/issues/10661

**Comment by greg0ire** [comment]
There even is a PR
