### ISSUE TITLE
[2.17.x,2.18.x] Failed getting entity with fetch eager property

### ISSUE THREAD

**Issue by dbannik** [doctrine/doctrine2#11091]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.17.x, 2.18.x

#### Summary

There is such a structure:
**AbstractRemoveControl**
**MobileRemoteControl**
**User**

Relationships:
**User** ---ManyToOne---> **AbstractRemoteControl**
**AbstractRemoteControl** ---OneToMany(fetch=Eager)---> **Collection**<**User**>

When querying from the database for User:
**2.17.x** - (Undefined array key "id" | TypeError : ReflectionProperty::getValue(): Argument 1 ($object) must be provided for instance properties)
**2.16.x** - Ok

#### How to reproduce

FunctionalTests https://github.com/doctrine/orm/pull/11090 #11262

**Comment by michnovka** [comment]
It seems we have a loop where while User is being hydrated, in the middle of it AbstractRemoteControl is being hydrated, and this due to eager fetching of User entity, tries to hydrate User entity again (before the original hydration is completed). However the User entity is hydrated at this point with remote_control pointing to null (because hydration was not finished)

This all seems to be introduced due to the changes here https://github.com/doctrine/orm/commit/76fd34f76607b1b96f381377c1c51df292c759aa

I spent some time debugging it, but I am not so familiar with the details and circumstances why the lazy loading of collections was changed, the removal (or even meaning) of SUBSELECT, so I cannot fix this.

**Comment by ghost** [comment]
Has anyone found a workaround?

I'd like to allow my team to upgrade doctrine/orm passed 2.16.3, but beginning with 2.17.0 all our relationships whose inverse side has `fetch: 'EAGER'` cause the TypeError.

**Comment by michnovka** [comment]
@greg0ire which PR closed this?

**Comment by greg0ire** [comment]
This one I think: https://github.com/doctrine/orm/pull/11090
