### ISSUE TITLE
Issue with Query Cache in Doctrine ORM Causing Cache Memory Overflow

### ISSUE THREAD

**Issue by alebedev80** [doctrine/doctrine2#11112]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     |  2.17.1

#### Summary

I am experiencing an issue with Doctrine ORM's query caching mechanism, leading to Redis memory overflow. This is primarily due to the way 'limit' and 'offset' values are handled in cached queries.

#### Current Behavior

In my production environment, Doctrine ORM caches each query including 'limit' and 'offset' as literal values in the SQL statement, rather than as parameters. As a result, every paginated request results in a new cache entry, with the only difference being the varying 'limit' and 'offset' values. This leads to an excessive number of cache entries in Redis.

#### How to Reproduce

- Configure Doctrine ORM with query caching, using Redis as the cache storage.
- Run a query that includes 'limit' and 'offset' clauses.
- Increment the 'offset' value (simulate pagination) and re-execute the query.
- Observe the creation of multiple cache entries in Redis for each query variation.

See test code [here](https://github.com/alebedev80/doctrine_orm_cache_overflow)

#### Expected Behavior

The expected behavior is for Doctrine ORM to treat 'limit' and 'offset' as parameters rather than literals in the query. This approach would allow for a single cache entry to be applicable to multiple paginated requests of the same query, thereby reducing the number of cache entries and preventing cache memory overflow.

Additional Information
Redis version: 7
PHP version: 8.2
DB: MySQL 8
Environment: Production
Addressing this issue is critical for optimizing query caching efficiency in Doctrine ORM, especially for applications that heavily rely on pagination.

**Comment by alebedev80** [comment]
Hey somebody!

**Comment by greg0ire** [comment]
Can you detail the "how to reproduce" section with code?

**Comment by alebedev80** [comment]
@greg0ire please check
https://github.com/alebedev80/doctrine_orm_cache_overflow

**Comment by greg0ire** [comment]
Looked into it thanks to your reproducer, and this is where the ORM does the hardcoding (actually, you can see it delegates that job to DBAL): https://github.com/doctrine/orm/blob/e50ae06fe786c2af91812cac50525a701c69a4e1/lib/Doctrine/ORM/Query/SqlWalker.php#L573

Now we need to figure out why it's done like this.

**Comment by greg0ire** [comment]
Maybe it was just not possible to use parameter binding at the time, at least for some platforms: https://github.com/doctrine/dbal/issues/3459#issuecomment-463826007

**Comment by alebedev80** [comment]
@greg0ire maybe? In MySQL and PostgreSQL it's possible for sure. I think it should use parameters per any platforms which support parameters. For this package risky to use.

**Comment by greg0ire** [comment]
It's risky to use for you in your specific situation. Did anybody else complain about this before? If not, then it's not that risky, if yes, then you shouldn't open duplicate issues.

**Comment by alebedev80** [comment]
@greg0ire quite interesting approach. I think all the major corporations should adopt it. "I found a 0-day vulnerability here" - "we won't fix it because no one's complaining".  :)

Can you explain why you're using parameter in where condition but not in limit|offset?

**Comment by alebedev80** [comment]
@beberlei please help

**Comment by greg0ire** [comment]
This does not have to do with zero days, let alone security though, right? Also, not a major corporation here, in case you hadn't noticed.

Regarding the why, I believe the link I provided above explains why it's done like this: PDO limitation, maybe no longer relevant.

**Comment by alebedev80** [comment]
@greg0ire  1) the reason why created the ticket some bot parsed the API list and just increaed 'page' parameter infinitely and after some time Redis reached memory limit and service crashed. 2) in the my example repo [i implemented one more script to demonstrate how to use integer placeholder with PDO.](https://github.com/alebedev80/doctrine_orm_cache_overflow/blob/main/src/test_mysql_pdo.php)

**Comment by greg0ire** [comment]
I think our SECURITY.md should mention https://www.doctrine-project.org/policies/security.html

I'm AFK and will be for a week, so can't help much here. The next step would be to look into implementing a DBAL API that allows to use placeholders with limit and offset, and then leverage it in ORM.

**Comment by alebedev80** [comment]
> I think our SECURITY.md should mention https://www.doctrine-project.org/policies/security.html

Ooops!

"If you think that you have found a security issue in Doctrine, please don't use the issue tracker in GitHub and don't publish it publicly. Instead, all security issues must be sent to..."

>  The next step would be to look into implementing a DBAL API that allows to use placeholders with limit and offset, and then leverage it in ORM.

So what i should to do? Create issue in doctrine/dbal?

**Comment by greg0ire** [comment]
Yeah, creating an issue in the DBAL seems good. And let me delete some of the last messages

**Comment by beberlei** [comment]
Its confusing, the firstResult+maxResults are in `Query::getQueryCacheId`, but no clue why, they are not relevant I believe. The last change on that line was just coding styles. https://github.com/doctrine/orm/blame/2.17.x/lib/Doctrine/ORM/Query.php#L819

Could you paste the output of your test.php to the README.md of that repo? then i dont have to execute this myself.

**Comment by greg0ire** [comment]
@beberlei it's like that since 04832e2789086a0ee88826b97a9e39076d5f84be, prompted by https://github.com/doctrine/orm/issues/1859

**Comment by alebedev80** [comment]
@beberlei please review [README.md](https://github.com/alebedev80/doctrine_orm_cache_overflow/blob/main/README.md#testphp-output)

**Comment by alebedev80** [comment]
@beberlei some news?

**Comment by mpdude** [comment]
One challenge I see is that `\Doctrine\ORM\Query\SqlWalker::walkSelectStatement` returns a string, and thus we cannot make it use parameters... who would know about these parameters, who would bind their values? The parameter names and/or values would need to be returned alongside the SQL string and be dealt with by the calling code.

Maybe one way out would be to add new methods that allow to set _parameter names_ that shall be used in `LIMIT` and `OFFSET` clauses, and then have the same in DBAL to create the platform-specific SQL accordingly?

When choosing parameter names in an automated fashion, we need to take care that they are unique in case people do subqueries/subselects, to avoid parameter name collisions. At the same time, the names must not be random, otherwise they'd mess up the query cache as well. So, like predictable, unique parameter names used in queries that may not fully be constructed at the time the name is needed?

**Comment by mpdude** [comment]
Regarding the question why `getQueryCacheId` puts the offset/limit into the cache key... that's because the cache key/id is used to bypass query -> SQL compilation. When the resulting SQL contains the offset/limit as literals, we need to consider them in the lookup key.

**Comment by mpdude** [comment]
As I've said in the [DBAL issue](https://github.com/doctrine/dbal/issues/6246#issuecomment-1900271691) I don't believe this can easily be fixed or even prepared in DBAL, and then we'd also need similar changes here in ORM.

So I'd like to suggest another route:

Would it be possible to put (through a dedicated, additional interface?) the output walker into a dedicated "mode" where it uses a (random) placeholder string instead of the SQL expression for limit/offset handling? Then keep the placeholder name together with the unfinished SQL statement in the DQL->SQL cache, and fill in platform-specific limit/offset expressions at a later time, after the parserResult has been taken from the cache?

Cache key computation would probably need to know if this is going to work and only conditionally include offset/limit.

Things like `\Doctrine\ORM\Query::getSQL` need to be kept in mind, of course those need to return the full query as previously.

Update: Due to the way `\Doctrine\DBAL\Platforms\AbstractPlatform::doModifyLimitQuery` works (possibly constructing new SQL queries with the old query being a subquery), it cannot be a placeholder, but rather must be a full, deferred call to that method; and that means also other things (like the lock mode specific SQL) might need to be called after it.

**Comment by mpdude** [comment]
What cache are we talking about, the query (DQL->SQL) cache or the result cache?

**Comment by alebedev80** [comment]
> What cache are we talking about, the query (DQL->SQL) cache or the result cache?

@mpdude the query (DQL->SQL) cache

**Comment by alebedev80** [comment]
> Then keep the placeholder name together with the unfinished SQL statement in the DQL->SQL cache, and fill in platform-specific limit/offset expressions at a later time, after the parserResult has been taken from the cache?

@mpdude but in that case why need to use DQL->SQL cache at all if anyway after extracting SQL from the cache will be done some string manipulation?

**Comment by beberlei** [comment]
The query cache does not need this theoretically, because we can call modifiyLimit... on the resulting sql coming from the cache. 

This should not even be a problem with paginator, because that has query hints that change the cache id

**Comment by mpdude** [comment]
Do we consider the ParserResult class or the AbstractSqlExecutor and subclasses as part of our public API?

The SqlWalker for sure is, it is subclassed in a documentation example.

**Comment by alebedev80** [comment]
Hey! how is it going?

**Comment by mpdude** [comment]
I need to find spare time to think through Benjamin‘s review 😉

**Comment by alebedev80** [comment]
@mpdude so you are only who is an able to fix it?

**Comment by alebedev80** [comment]
Half year passed. do you plan to fix it?

**Comment by mpdude** [comment]
I‘d love to fix it since I already put much effort into it and I think it’s feasible. Also I still have this item on my personal to-do list.

However, unless being paid for it, I’d have to do this in my spare free time, which is rather limited at the moment 😔. I’ll see what I can do, but no promises given.

**Comment by mpdude** [comment]
#11188 has just been merged into 2.20.x, and I think it fixes this issue here.
