### ISSUE TITLE
Unnecessary calls to doLoadMetadata

### ISSUE THREAD

**Issue by trsteel88** [doctrine/doctrine2#11113]
I've been using Blackfire and I've noticed that if you include a \DateTime object in a query, it gets passed through doLoadMetadata. Doing so, triggers a warning in Blackfire that all metadata should be cached.

In my scenario, we are caching metadata (and it's pre-cached during the warmup). However, because \DateTime obviously isn't an Entity, it gets passed to doLoadMetadata on every use.

Is there any way to prevent this from happening?

Here is the example query:

```php
return $this->createQueryBuilder('project')
            ->andWhere('project.updatedAt < :date')
            ->setParameter('date', new \DateTime('today'))
            ->setMaxResults(30)
            ->getQuery()
            ->toIterable()
        ;
```

**Comment by ostrolucky** [comment]
Wrong repository. You might try https://github.com/doctrine/orm

**Comment by greg0ire** [comment]
Transferred :)

**Comment by derrabus** [comment]
What is the performance impact of calling `doLoadMetadata()` on a `DateTime` object?

**Comment by mbabker** [comment]
Seeing this made me dig in a little bit since we have a number of queries supporting `DateTime` parameters.  As far as actual performance goes, it looks negligible at best in the app I looked at (in a frequently running cron command on production where a `DateTime` parameter is triggering the metadata loader, with Symfony's default system cache, it's spending ~3ms trying to load metadata here).

> Is there any way to prevent this from happening?

Explicitly set the third parameter in your `QueryBuilder::setParameter()` calls as that'll keep the ORM from getting into the parameter type inference/resolving logic when running the query.

**Comment by greg0ire** [comment]
Thanks for looking into this @mbabker ! Closing since it seems there is a way out :)

**Comment by trsteel88** [comment]
Thanks for the info.
