### ISSUE TITLE
Allow extending query parser

### ISSUE THREAD

**Issue by lstrojny** [doctrine/doctrine2#5656]
I would like to be able to extend the parser class and add e.g. custom operators from MySQL. Currently the only workaround is to use a function. See these examples:

 - https://stackoverflow.com/questions/29578168/custom-operator-in-doctrine-dql
 - https://github.com/semin-lev/ltree-extension-bundle/blob/master/DqlFunction/LtreeOperatorFunction.php

Using a function here is clumsy and reduces readability of the DQL query very much.

While `Doctrine\ORM\Query\Parser` could be extended `Doctrine\ORM\Query` is final therefore a different parser class cannot be registered.

**Comment by Ocramius** [comment]
@lstrojny why not using directly SQL for such a specific operation (considering that readability of the query is important to you here)?

**Comment by lstrojny** [comment]
An example is the MySQL null safe comparison operator `<=>` that is so incredibly practical, that I want to use it all over the place without falling back to SQL.

**Comment by Ocramius** [comment]
@lstrojny and `SAFE_COMPARISON(a, b)` wouldn't work? I realize that it is annoying, but we are actually thinking of moving the parser to a [`Hoa\Compiler`](https://github.com/hoaproject/Compiler/) based solution, and extensibility seems to be a problem with syntaxes (any of them)

**Comment by lstrojny** [comment]
Unfortunately it’s even {{SAFE_COMPARISON(a, b) = 1}} which looks awful to me, so nah, I don’t find it good enough.

**Comment by guilhermeblanco** [comment]
@lstrojny unfortunately what you're trying to do is changing the way we parse and AST. This is far from a trivial task. Currently DQL parser is an LL(k), which means at the point we need to identify which kind of comparison we're dealing with (ie. a.b = 1, a.b IN (?), foo(a.b) > 10, etc), we need to lookahead until we reach the operator (in your case it would be <=>), then backtrack and start the parsing analysis over the appropriate grammar rule.

Moving to an equivalent in a language, it's the same as trying to request PHP to allow extending its parser because you want a new operator ($a <=> $b) to be recognized to run over Zend VM. Not easy, not originally considered and extremely error prone.

-1 from me.
