### ISSUE TITLE
Method find() in /orm/lib/Doctrine/ORM/EntityManager.php does not only return object and null

### ISSUE THREAD

**Issue by giginos** [doctrine/doctrine2#5666]
The method find() in class /orm/lib/Doctrine/ORM/EntityManager.php has the expected values object or null. If you have a look into that method you will find the following code around line 417:

``
// Check identity map first
 if (($entity = $unitOfWork->tryGetById($sortedId, $class->rootEntityName)) !== false) 
..
return $entity; // Hit!
``

The returned value $entity does also return boolean so the inline-documentation of find()-Method is not correct.

You should check, if allowing boolean as a return-value is valid, too or if you have to modify "return $entity;" for that case.

Regards,
Rafael Kutscha

**Comment by Ocramius** [comment]
> The returned value $entity does also return boolean so the inline-documentation of find()-Method is not correct.

The [`tryGetById`](https://github.com/doctrine/doctrine2/blob/02eaf6a17a7260baa60144ca355a3c3fd332488a/lib/Doctrine/ORM/EntityManager.php#L418) call will always return `object|false` (which is why it's annotated as `object|book`). That call will never return `true`.

In all the cases where `$entity = false`, the return value [will](https://github.com/doctrine/doctrine2/blob/02eaf6a17a7260baa60144ca355a3c3fd332488a/lib/Doctrine/ORM/EntityManager.php#L447) [be](https://github.com/doctrine/doctrine2/blob/02eaf6a17a7260baa60144ca355a3c3fd332488a/lib/Doctrine/ORM/EntityManager.php#L459) [based](https://github.com/doctrine/doctrine2/blob/02eaf6a17a7260baa60144ca355a3c3fd332488a/lib/Doctrine/ORM/EntityManager.php#L462) on the return value of [`EntityPersister#load()`](https://github.com/doctrine/doctrine2/blob/02eaf6a17a7260baa60144ca355a3c3fd332488a/lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php#L200) or [`EntityPersister#loadById()`](https://github.com/doctrine/doctrine2/blob/02eaf6a17a7260baa60144ca355a3c3fd332488a/lib/Doctrine/ORM/Persisters/Entity/EntityPersister.php#L212).

**Comment by giginos** [comment]
Hi @Ocramius, but the docblock says: "@return object|null The entity instance or NULL if the entity can not be found." - so i do not expect "false" as a valid return for method find(). Dont you aggree?

**Comment by giginos** [comment]
"valid" means object or null in this case.

**Comment by Ocramius** [comment]
@giginos the method will only return either `object` or `null`, nothing else.

**Comment by giginos** [comment]
@Ocramius : You're right! I've made a mistake in my if-clause "if($obj = $entityManager->find($me) !== null)..." So $obj got "true" :-) Thanks for your replys.

**Comment by Ocramius** [comment]
:+1:
