### ISSUE TITLE
spatial index

### ISSUE THREAD

**Issue by collmomo** [doctrine/doctrine2#5678]
There's no mention of this in the documentation
`CREATE SPATIAL INDEX sp_index ON geom (g);`
https://dev.mysql.com/doc/refman/5.7/en/creating-spatial-indexes.html

**Comment by Ocramius** [comment]
Spatial indexes are engine-specific. We do not support them in core.

**Comment by collmomo** [comment]
I don't know what that means but I found the documentation here http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/changelog/migration_2_5.html

**Comment by octaharon** [comment]
But you support engine-specific "Options" still, don't you?
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annref-index
So there's an obvious contradiction.
Also since "@index" has an undocumented "flags" property, it could be super easy to provide

Do you possibly have a recipe on how I can still have spatial indexes in my DB?

I'm not saying that you _should_ support engine-specific things, but I don't see any real way of having a spatial index now without creating a shitlload of code which intercepts all of doctrine table-related events, circumvents sql generator and so on,  while for the result I only need to add just *one word* to the query. That's completely bizarre
