### ISSUE TITLE
Doctrine Query Builder and Custom Types

### ISSUE THREAD

**Issue by Gladhon** [doctrine/doctrine2#5695]
I am using a custom type, as entity id. 
unfortunately if i'm using the query builder, the custom type wouldn't be parsed automatically, it just using  ParameterTypeInferer::inferType, which doesnt support any custom type.

Could we change that ?

**Comment by Padam87** [comment]
Related: https://github.com/Atlantic18/DoctrineExtensions/pull/1546

**Comment by Majkl578** [comment]
This is a serious problem, which also applies to builtin DateTimeTz type where the inferer fails to detect it and thinks it's DateTime instead, effectively dropping timezone information. Really nasty thing to debug.

As a workaround, setParameter() has 3rd parameter to explicitly specify type.
```php
->setParameter('time', $time, Type::DATETIMETZ)
```
Works with custom types too.

**Comment by Padam87** [comment]
@Majkl578 Yep, exactly this. We have had problems with custom (money) types as well.

**Comment by Ocramius** [comment]
This cannot be automagically fixed without having the `Type` API provide a `::matchesValue($value)` API, for example. Even then, the matching would still be quite weak. As an example, taking the problem above (`DateTime` vs `DateTimeTz`), a `DateTime` [always has an assigned `DateTimeZone`](https://3v4l.org/BaRM4).
I don't see this being solved in the near future, since the types API is quite inflexible, BC-wise, but a clear resolution path is not visible to me either. Explicit type passing is the correct approach here, and is also the safest solution.

**Comment by Gladhon** [comment]
@Ocramius i would propse to solve this problem on the higher ORM level than on DBAL Type.  Like it is done in BasicEntityPersister->getType when you use the findBy method.
