### ISSUE TITLE
registerAnnotationClasses

### ISSUE THREAD

**Issue by juliangut** [doctrine/doctrine2#5802]
Is it possible to have an registerAnnotationClasses method on AnnotationDriver (as in mongodb-odm) so it is not mandatory to call Doctrine\ORM\Configuration::newDefaultAnnotationDriver or AnnotationRegistry::registerFile with the correct path?

Mongodb-odm:
https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php#L51

**Comment by Ocramius** [comment]
When not using the setup facility, you are simply required to build the annotation driver yourself, or to simply use `AnnotationRegistry::registerLoader('class_exists`)` (to force autoloading of annotations).

We plan to drop this sort of complexity overall, rather than making it "easier" to set up things.

Closing as `won't fix`

**Comment by juliangut** [comment]
OK, thanks for the class_exists hint. It has been 12 days since I posted this issue so I decided to create the PR

**Comment by Ocramius** [comment]
@juliangut no problem. Sorry for the timing, I get to pick up a fraction of what hits my inbox, and that with delays.
