### ISSUE TITLE
Escaping field names

### ISSUE THREAD

**Issue by Maxiking1011** [doctrine/doctrine2#5843]
I can't use field names like group, from, database, ... because it is not escaped with ` - There is no functionallity to make doctrine use clean SQL Code

**Comment by Ocramius** [comment]
See http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases

Also, you can tell doctrine to quote by default (use a quoting strategy for that), but it may clash with your system due to the reasons mentioned above.
