### ISSUE TITLE
can  DateTime objects turn to string in query results?

### ISSUE THREAD

**Issue by akmumu** [doctrine/doctrine2#6105]
sometimes i don not need the DateTime obj,but only need the string to display

**Comment by Ocramius** [comment]
`array_map()` over the results and replace the `DateTime` instances with `string` via `DateTime#format()`

**Comment by akmumu** [comment]
i known this way,bug do not want to array_map every,and thanks a lot

**Comment by Ocramius** [comment]
Doctrine would have to do it for you with some complicated contraption,
while the operation itself takes 3 CLOC: just do it

On 27 Oct 2016 08:36, "Qinglong Zhang" <notifications@github.com> wrote:

i known this way,bug do not want to array_map every,and thanks a lot

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/issues/6105#issuecomment-256558842>,
or mute the thread

**Comment by akmumu** [comment]
ok，thanks
