### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by bilougit** [doctrine/doctrine2#6131]
My entity Ranking it related to my other entity User through a ManyToOne relationship. So the foreign key user_id lives in the ranking table.

When I get a ranking through find method for instance, it loads partially the related user entity. But when I try to access a user field which is not the PK an error shows up although the user does exist in the database
```
Entity of type 'AppBundle\Entity\User' for IDs id(155) was not found
```

After I figure out that the problem is that I have an enabled doctrine filter, it turns out that when doctrine is asked to send a user field other than the ID, it performs the sql query but with a new element in the condition join added by the doctrine filter, it returns nothing.

Wouldn't be better and more accurate to have an error that says exactly what wasn't found? 

**Bad**
```
Entity of type 'AppBundle\Entity\User' for IDs id(155) was not found
```

**Good**
```
Entity of type 'AppBundle\Entity\User' for IDs id(155) and """added condition of the doctrine filter""" was not found
```

**Comment by Ocramius** [comment]
The proxy/hydration system can't know about why the association wasn't loaded: it just tries to load something by identifier and is given back a `null` result.

This is a very typical problem of SQL filters applied to graphs, since filters "shadow" part of your database, but aren't considering FKs when doing so (nor can do that).

Closing as `can't fix`
