### ISSUE TITLE
Use single entity and map it to multiple tables (dynamically set table name)

### ISSUE THREAD

**Issue by noisemaker00** [doctrine/doctrine2#6226]
I need to map a single entity (eg: CustomersOrdersY.php) to a multiple table, on the base of the year. Inside my class there's a field wich contains the year and I need to save record in the corrisponding table.
Example:
If the year in the class object was set to 2016 I need to save entity in: "customers_orders_2016"

Is that possible with the framework?

**Comment by lcobucci** [comment]
@noisemaker00 that's not supported since it's not the responsibility of an ORM.

I assume that you want to do that because your data increased a lot and everything is slow... if that is the problem you can try to use table partitioning to solve it, like [this for MySQL](http://dev.mysql.com/doc/refman/5.7/en/partitioning-overview.html).
