### ISSUE TITLE
Load class metadata change problem

### ISSUE THREAD

**Issue by danitome24** [doctrine/doctrine2#6361]
Hi,

I'm developing with DDD and doctrine and I would use embeddable for Value Objects. In my code, there are some Value Objects that I could reuse but due to a legacy code, these columns on database are different named. So I thought that I could update it on `loadClassMetadata` doctrine event. I also use Symfony.

To get this achievement I've started only assigning the embeddable to an entity from doctrine event like the following:
![image](https://cloud.githubusercontent.com/assets/7501990/24343373/621354a6-12c6-11e7-8f6c-f5e9a628382b.png)

This code works and on dump I can see the embeddable Location object into embeddables array. The problem is when I fetch something and this Value Object (location) is null on my entity (Hotel). 

Something wrong?

Versions:

Package | Vendor
------------ | -------------
Doctrine | 2.5.4
Symfony | 3.2.1

**Comment by lcobucci** [comment]
In general, what you would have to do is actually use the `@AttributeOverrides` annotation on you class using `embeddable.attribute` as name but due to the [current limitation](https://github.com/doctrine/doctrine2/pull/6151#issuecomment-271432401) you can't really do it at the moment.

I think you're having this issue for the same reason we can't override embeddable objects.

**Comment by danitome24** [comment]
How can I use `@AttributeOverrides` in YAML configuration? @lcobucci

**Comment by lcobucci** [comment]
@danitome24 https://github.com/doctrine/doctrine2/blob/1aa02f9afcb374d7d3060f960fa8ce096bf71369/lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php#L630

But I recommend you to move away from YAML since it's already removed from the next major release.

**Comment by danitome24** [comment]
Thanks a lot!

I've heard about it... There's any automatic way to move from YAML into XML config files? O I've to write again all my config files? @lcobucci

**Comment by danitome24** [comment]
@lcobucci Two last questions:

1. Why is YAML going to be removed? Performance? 
1. When is going to be developed this feature? I'm waiting for it... if need help...

Thanks a lot :+1:

**Comment by lcobucci** [comment]
> 1. Why is YAML going to be removed? Performance?

Also, YAML it's a mess and we had tons of invalid issues because of syntax errors. You can see more on https://github.com/doctrine/doctrine2/pull/5932#issuecomment-233593524

> 2. When is going to be developed this feature? I'm waiting for it... if need help...

At the moment we're working on different things so it would be amazing if the community could send a PR to `master` that fixes that (maybe you?).

**Comment by danitome24** [comment]
@lcobucci Thanks a lot...maybe you'll have a PR from me ;). Closing issue!!
