### ISSUE TITLE
Replace entity defintion

### ISSUE THREAD

**Issue by core23** [doctrine/doctrine2#6504]
I have an defintion for a `Location` entity under the namespace `Acme\LocationBundle` and want to extend this defintion in another bundle named `Acme\VisitBundle`. The only new thing on the extended `Location` entity is a list of multiple `Visit`s based on a OneToMany mapping.

I stumbled upon the [inheritance docs](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html) which explain some inheritence mappings. AFAIK the inheritance mapping is only useful if you add new fields (like a string, integer, etc.) but they say nothing about associatio mappings.

Is it possible to extend (or replace) the entity definition without using table inheritance, so I could call Location::getVisits on any entity in the `Acme\LocationBundle` and `Acme\VisitBundle`?

**Comment by Ocramius** [comment]
@core23 to extend an entity, you will need to subclass it, or else the original definition may not work as expected anymore (don't change the original definition, as it's not the business of your new bundle, and you may break things)

**Comment by core23** [comment]
Thanks for the explanation @Ocramius 

What about removing an entity defintion. All my mapping files are location under `Resources/config/doctrine` and will be loaded by the DoctrineBundle. 

Is there a way to forbid loading a specific file or remove it after loading the defintions? So doctrine won't know the original entity and I can replace it completly with the entity located under `Acme\VisitBundle`

**Comment by Ocramius** [comment]
> What about removing an entity definition. 

How will the original code behave then?

**Comment by core23** [comment]
The `Location` entity in the original bundle has no dependencies to other entitys. So this should be no problem after all.

**Comment by Ocramius** [comment]
The other bundle still relies on it though, so replacing it may break that logic.

All of this can be done via [`loadClassMetadata` listeners](https://github.com/doctrine/doctrine2/blob/fc67b398a1efd3d61837778e2cda2d05a395778c/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L240-L243), but I'm closing here, because it shouldn't be done, especially across library boundaries.

If you need to re-define an entity, copy the definition, the mappings, then adapt and make a new table and new associations.
