### ISSUE TITLE
Doctrine FindBy doesn't work with time type

### ISSUE THREAD

**Issue by moralesfelipe** [doctrine/doctrine2#6584]
Trying to retrieve a entity using findBy
But doctrine returns an empty array 
I tried using DateTime with date 1970-01-01 but is the same

**Comment by Ocramius** [comment]
That's usually because of type conversion adding also hours/minutes/seconds.

Can you write a failing test case so we compare it against our development
branch?

On 28 Jul 2017 1:42 AM, "moralesfelipe" <notifications@github.com> wrote:

Trying to retrieve a entity using findBy
But doctrine returns an empty array
I tried using DateTime with date 1970-01-01 but is the same

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/issues/6584>, or mute the thread

**Comment by moralesfelipe** [comment]
Yes,sorry I haven't check the seconds. That was the issue
