### ISSUE TITLE
Question: Why is Doctrine\ORM\EntityRepository#getEntityManager() protected?

### ISSUE THREAD

**Issue by spackmat** [doctrine/doctrine2#6615]
Hi,

I am refactoring my Symfony controllers to get the EntityRepositories injected instead of the whole EntityManager. This works fine, but in some cases (transactions, changing listeners etc.), I still need access to the EntityManager.

But the Doctrine\ORM\EntityRepository#getEntityManager() method is protected. This surely is intentional, so my question is: Would it be bad practice to access the EntityManager through (injected) repositories? Or are there other reasons for the protection?

Greets,
spackmat

**Comment by Ocramius** [comment]
> Would it be bad practice to access the EntityManager through (injected) repositories? 

Yes, it is out of the responsibility of the `EntityRepository` to provide its dependencies to you. The same applies to basically any service. The method should be `private`, but it was made `protected` since this class was initially designed for inheritance.

You'd inject a separate `EntityManager`.
