### ISSUE TITLE
A Native Sql is committing the current transaction

### ISSUE THREAD

**Issue by Narcotic** [doctrine/doctrine2#6628]
Hello Doctrine,

Is there a way to execute a native sql query (calling a stored procedure) without auto commiting the current open transaction?

Example:
```php

$entityManager->beginTransaction();
...
$entityManager->merge($event);
$entityManager->flush();
...
$sql = <<<SQL
    CALL eventsForPeriod_EventList();
SQL;

$all = $this->em->getConnection()->fetchAll($sql);
// => at this point the transaction is commited :/
...
$entityManager->rollback();

```
Thank you !

Jody

**Comment by Ocramius** [comment]
Only the inner transaction should be committed there: the outer one is still active. You can check the transaction nesting level on the connection.

**Comment by Narcotic** [comment]
You're right, the nesting level is at 1 when the `$entityManager->rollback();` will be done.

But, I don't know why, my data are persisted after the fetchAll() :-/ If I comment the line, it is not!

Any idea?

Thank you for your fast response.

**Comment by Ocramius** [comment]
On MySQL, transaction nesting is emulated via savepoints: I think we need
more integration tests for MySQL to see if it actually behaves like that
correctly or if more flags/server-side settings are needed. Also check that
you aren't running on MyISAM, which is just a wreckage.

On 16 Aug 2017 4:28 PM, "Jody Lognoul" <notifications@github.com> wrote:

You're right, the nesting level is at 1 when the $entityManager->rollback();
will be done.

But, I don't know why, my data are persisted after the fetchAll() :-/ If I
comment the line, it is not!

Any idea?

Thank you for your fast response.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/issues/6628#issuecomment-322789445>,
or mute the thread

**Comment by Narcotic** [comment]
Hello,

I finally  found that the commit was being caused due to a coding error in my stored procedure... Before the creation of the temporary Table, I was issuing a Drop Table statement, without the **TEMPORARY** keyword, which was causing an auto-commit.

https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

So, the issue wasn't Doctrine wise, sorry about that.

Thanks btw.

**Comment by Ocramius** [comment]
Argh, yes, MySQL still doesn't have transactional DDL, but Doctrine DOES create temporary tables for some ManyToMany operations, and that's not fixable.

**Comment by lcobucci** [comment]
@Narcotic should we close this?

**Comment by Narcotic** [comment]
Yes!

**Comment by lcobucci** [comment]
Closing as `invalid` since it's not an ORM issue.
