### ISSUE TITLE
2.6 (dev-master at present) excludes all stable versions of symfony/yaml

### ISSUE THREAD

**Issue by asgrim** [doctrine/doctrine2#6639]
Latest version is not installable at the moment without explicitly allowing the dev version of symfony/yaml because it's not stable yet. This may have impact on the imminent release of ORM 2.6.

**Comment by asgrim** [comment]
The cause is the `conflict` with any version less than 3.4, introduced in https://github.com/doctrine/doctrine2/commit/40515472c109b636bf857676232e0619cf182883

**Comment by Ocramius** [comment]
This is hilarious: we finally managed to remove Yaml support 😂

**Comment by stof** [comment]
actually, I would remove the usage of the constant without bumping the min version. This constant was added in symfony/yaml 3.3 (so undefined constant also applies to 3.2 and older in the old code of https://github.com/doctrine/doctrine2/pull/6630/files btw) to add a way to force evaluating keys as string to go toward more compliant parsing by default. Just after the release of 3.3 (so too late to revert the introduction of the constant without going through deprecation), we figured out a better upgrade for users to do (and even 3.3 deprecation warnings suggest the better way now instead of suggesting the constant IIRC): actually putting quotes around the key when the unquoted value would not be a YAML string.

And this means that your code is actually working with any version of the Yaml component (you now have again the same code than in the Symfony 3.2 time). The bump of the min version was a mistake in #6630 due to a bad analysis of when the constant was available.

**Comment by Ocramius** [comment]
@stof if that's alright, I'll just remove the `conflict` then.

Still, had a good and loud laugh :D

**Comment by stof** [comment]
@Ocramius yes, reverting the conflict rule is what you need here.

Too bad that we came up with this `PARSE_KEYS_AS_STRINGS` feature and released it before finding the right change to do (it's actually not the first time this happened to us. We had this in Symfony 2.3 adding synchronized services in the DIC to support better the `request` service, and the RequestStack idea was stuck in discussion while releasing it and so came in 2.4 only and synchronized services became useless... Nobody's perfect).

**Comment by Majkl578** [comment]
See #6658.
