### ISSUE TITLE
where clause requiring an operand

### ISSUE THREAD

**Issue by tok-amsiq** [doctrine/doctrine2#6688]
I wouldn't exactly define this as an issue with doctrine, but it's giving me some problems in my project. 
I can't find a way to force the querybuilder to accept a where clause as simply being true, without having to set it to '= true'.
In SQL you can simply make a statement that goes like:

    SELECT * FROM users WHERE email_validated;

Is there any way that this is possible to achieve with the querybuilder? It'd look something like:

    $this->createQueryBuilder('users')->where('users.email_validated');

Since it expects an operand, it throws the following exception:

    [Syntax Error] line 0, col -1: Error: Expected =, &lt;, &lt;=, &lt;&gt;, &gt;, &gt;=, !=, got end of string.

I hope I'm making myself clear, otherwise I'd be happy to explain further, thanks in advance.

**Comment by kejwmen** [comment]
> I can't find a way to force the querybuilder to accept a where clause as simply being true, without having to set it to '= true'.

It's not possible, but why do you want to do that?

This is how [DQL grammar](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#conditional-expressions) looks like (look at `SimpleConditionalExpression`).

`QueryBuilder` does not know about field types (because it's not its responsibility) to magically add conditional, so I see no possibilites of allowing that.

Even if somebody have an idea how to introduce that - for me it brings additional code to maintain for no real gain.

**Comment by tok-amsiq** [comment]
Thanks for the reply @kejwmen!

It was a quite unique case, but I was using a doctrine extension introducing MBRContains to calculate distances between two points.
I therefore had a spatial index on the point column, which is kinda critical if I want a response lower than 3 seconds. MBRContains doesn't use the index if you set it to '= true'. And that's not just in doctrine, it doesn't use the index unless I avoid the '= true' in a native SQL either. 
But since this wasn't a common issue, I figured that a CustomSQLWalker  was my best option and it's working just as intended :-)
