### ISSUE TITLE
Unit of work : get the count of scheduled insertions / updates / deletes 

### ISSUE THREAD

**Issue by arthursp** [doctrine/doctrine2#6702]
It will be interesting to have the count of scheduled update / insert /delete in the unit of work, 

Currently there is getScheduledEntityInsertions( ), getScheduledEntityUpdates( ), getScheduledEntityDeletions( ), but it return arrays.

**Comment by alcaeus** [comment]
So, um, call count() on them?

**Comment by Ocramius** [comment]
Closing as per @alcaeus' answer

**Comment by arthursp** [comment]
"So, um, call count() on them?"

The objetctive was to increment a counter on each add / update / delete and get the count directly without counting on a full array of entities ...

**Comment by Ocramius** [comment]
That's up to you to do - no advantage in that ORM-side

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by alcaeus** [comment]
> The objetctive was to increment a counter on each add / update / delete

What good would that do? For one, updates are only available once changeset computation has been done (which is normally done inside a `commit()`).

> get the count directly without counting on a full array of entities

You are aware that there is no computational overhead in returning the "full array of entities" and `count` is rather fast (except maybe if your array has hundreds of thousands of elements, in which case I'd assume you have a different performance problem on your hands before that)?
But sure, I'll bite: what's the use case of storing a counter instead of just running `count`?

**Comment by arthursp** [comment]
@alcaeus An import script , and I have thousand of entities
@Ocramius ok if you think so, you are the expert

**Comment by Ocramius** [comment]
@alcaeus SLOW!

  > @alcaeus An import script , and I have thousand of entities

@arthursp counting/incrementing is really up to you there: if you even work in a controlled environment, then you don't need any `UnitOfWork` facilities, as you know what you are doing, and can count the operations manually.

**Comment by arthursp** [comment]
@Ocramius yes but if the ORM can help me for free :)
But I respect you point of view : not the ORM role.
