### ISSUE TITLE
createNamedNativeQuery vs createNativeNamedQuery

### ISSUE THREAD

**Issue by ncraike** [doctrine/doctrine2#6729]
`Doctrine\ORM\EntityManager` has a method `createNamedNativeQuery()`.

`Doctrine\ORM\EntityRepository` has a method `createNativeNamedQuery()`.

They each do similar things, but have access to a slightly different set of queries. (For example, the `EntityRepository` method knows about queries defined through entity annotations, while `EntityManager doesn't.)

To avoid confusion and typos, could these two methods be given the same name? Or (to preserve backwards compatibility), could both classes be given aliases for these methods with the alternate spelling?

Note that the documentation [on the use of native queries](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/native-sql.html) doesn't show either method being called.

**Comment by Ocramius** [comment]
They should both be dropped, tbh: native queries are to be kept in your
codebase, and registering them with the EntityManager has no advantages
whatsoever

**Comment by ncraike** [comment]
The advantage I found was that by defining the native query in Doctrine (through annotations on my entity/model class), I could concisely describe the `ResultSetMapping` used to map my native query's results into actual entities.

I'm using the `resultClass` option, since my native query returned all fields of a single entity, like the annotations demonstrated [in the docs](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/native-sql.html):

```php
<?php
namespace MyProject\Model;
    /**
     * @NamedNativeQueries({
     *      @NamedNativeQuery(
     *          name           = "find-by-id",
     *          resultClass    = "Address",
     *          query          = "SELECT * FROM addresses"
     *      ),
     * })
     */
   class Address
   {
        // ....
   }
```

This was useful for me because I didn't have to spend several lines in my repository class manually defining a `ResultSetMapping` of every field of my entity, like:

```php
$rsm = new ResultSetMapping;
$rsm->addEntityResult('User', 'u');
$rsm->addFieldResult('u', 'id', 'id');
$rsm->addFieldResult('u', 'name', 'name');
```

**Comment by Ocramius** [comment]
That can be fixed via a helper method. As it currently stands, named
queries are just a silly lookup map with lots of added ORM coupling that is
just not worth it 😁

On 26 Sep 2017 09:44, "Nathan Craike" <notifications@github.com> wrote:

The advantage I found was that by defining the native query in Doctrine
(through annotations on my entity/model class), I could concisely describe
the ResultSetMapping used to map my native query's results into actual
entities.

I'm using the resultClass option, since my native query returned all fields
of a single entity, like the annotations demonstrated in the docs
<http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/native-sql.html>
:

<?phpnamespace MyProject\Model;    /**     * @NamedNativeQueries({
*      @NamedNativeQuery(     *          name           =
"find-by-id",     *          resultClass    = "Address",     *
 query          = "SELECT * FROM addresses"     *      ),     * })
*/   class Address   {        // ....   }

This was useful for me because I didn't have to spend several lines in my
repository class manually defining a ResultSetMapping of every field of my
entity, like:

$rsm = new ResultSetMapping;$rsm->addEntityResult('User',
'u');$rsm->addFieldResult('u', 'id', 'id');$rsm->addFieldResult('u',
'name', 'name');

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/issues/6729#issuecomment-332114332>,
or mute the thread

**Comment by lcobucci** [comment]
I'll close this issue since @Ocramius already provided an explanation. Feel free to reopen if you think it's needed.
