### ISSUE TITLE
OneToMany JoinColumn options where cause

### ISSUE THREAD

**Issue by ushatel** [doctrine/doctrine2#6938]
Hello, 

For the moment it looks like we have it possible to join just a single column when processing the join. 

Most SQL engines allow the multiple columns "join <table> on <column>=:1 and <column>=:2" statements. 

Possible solution: 
Add similar to the ["@ Index"](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annref-index) 
 `options={"where": "(((id IS NOT NULL) AND (name like 'Mr%')) AND (email like '%@%'))"}`

Why it is important: 
With such options="where()" that will be added to the JOIN ON cause it would be possible to save the time for the separated custom SELECT when do we need to restrict JOIN select for the single field like 'language like "%English%" or currency like "%Euro%"'. 

Could this make scense? 

Thank you for the attention and wish you good Christmas!

**Comment by Ocramius** [comment]
While at surface it looks like a good idea, it is actually a terrible feature.

The reason is simple: the ORM operates under the assumption that the in-memory data structure mirrors the db data.

Addibg conditional filters on associations makes this extremely unreliable, as the data you save may no longer be visible after a refresh operation (while still there).

We already provide such functionality via SQL filters abd it has bitten many, many, many people due to broken proxy references to filtered records.

Therefore this is not possible/feasible. What you want is a read model rather than an association in your entities.
