### ISSUE TITLE
Error for delete query without alias since 2.6.0

### ISSUE THREAD

**Issue by dmaicher** [doctrine/doctrine2#6939]
This used to work with `2.5.x`:

```php
$em->createQueryBuilder()
    ->delete(MyEntity::class)
    ->getQuery()
    ->execute();
```

Now with `2.6.0` I get this error:

```
[Syntax Error] line 0, col -1: Error: Expected Doctrine\ORM\Query\Lexer::T_IDENTIFIER, got end of string. (Doctrine\ORM\Query\QueryException)
```

If I add an alias it works again:

```php
$em->createQueryBuilder()
    ->delete(MyEntity::class, 'e')
    ->getQuery()
    ->execute();
```

Is this BC break intentional?

**Comment by Majkl578** [comment]
Similar to #6932 (missing alias in FROM), it'll be caused by the same source.
As you can see [here in EBNF for 2.5.0](https://github.com/doctrine/doctrine2/blob/v2.5.0/docs/en/reference/dql-doctrine-query-language.rst#clauses), alias is actually supposed to be mandatory.

It should probably be fixed for 2.6.

**Comment by Tobion** [comment]
Can confirm the bug. I'm als affected with something like `$em->createQuery('DELETE FROM '.MyEntity::class)->execute();`.
I don't think the alias should be required for simple queries like this.

**Comment by lcobucci** [comment]
#7077 is fixing the BC-break and discussing the update of the grammar to align with JPA 2.2 for `v2.6.x` and `v3.0`

**Comment by Ocramius** [comment]
Handled in #7077
