### ISSUE TITLE
Error if use IN-clause inside a SUM function

### ISSUE THREAD

**Issue by webgnome** [doctrine/doctrine2#7533]
I want to order my result by by the sum of condition matches

`SUM(some_column IN (val1, val2, val3))`

As i understand the code of symfonys doctrine Bundle the "AVG" | "MAX" | "MIN" | "SUM" | "COUNT functions do only except DISTINCT inside the sum parenthesis.

At the moment i use

`
entityManager->getConnection()->prepare(...)
...->execute ...
`

After that i have to do a second call over the repository class

1. Am i Right with my assumptions?
2. Is there any way to use an IN-clause inside the sum function without bypassing the ORM?
3. Can this be a new feature, or is it a Bug?

**Comment by Ocramius** [comment]
> Am i Right with my assumptions?

Correct, `DISTINCT` isn't allowed there.

 > Is there any way to use an IN-clause inside the sum function without bypassing the ORM?

It is OK to use SQL for such computations

 > Can this be a new feature, or is it a Bug?

It's a `won't fix` upfront, since `SUM(expr)` is not really supported by all vendors. If you want to support it, you'd start by providing test scenarios, and verifying that they run on all DBAL platforms.

Meanwhile, closing here, since relying on SQL is an acceptable/simple tradeoff.
