### ISSUE TITLE
Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getSequenceNextValSQL' is not supported by platform.

### ISSUE THREAD

**Issue by ThibaultVlacich** [doctrine/doctrine2#8614]
Since 2.8.2, I'm getting this error when I'm trying to persist an object on a MariaDB server.

```php
$this->getDoctrine()->getManager()->persist($obj);
```

Is throwing the following exception:

> Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getSequenceNextValSQL' is not supported by platform.

I have a hard time reproducing the issue on other databases. But I isolated ORM 2.8.2 (and further) as being the source  of the issue. As soon as I downgrade to 2.8.1, everything is fine.

**Comment by BenoitDuffez** [comment]
What was the cause?

**Comment by UtechtDustin** [comment]
I had the same issue, in that case i forgot the serverVersion in the .env.(local).
https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration

**Comment by BenoitDuffez** [comment]
I still reproduce (not all the time, it's erratic), even with:
```DATABASE_URL: mysql://xxx:yyy@zzz/www?serverVersion=mariadb-10.3.34```
(also tried with `5.7`)

**Comment by BenoitDuffez** [comment]
I had a `#[GeneratedValue(strategy: "AUTO")]`, and it looks like replacing with `#[GeneratedValue]` fixed the issue. That's weird, because AUTO should default to a _identity_ strategy, and not a _sequence_ strategy. But the stack trace clearly shows it used a _sequence_:

```
{
    "class": "Doctrine\\DBAL\\Exception",
    "message": "Operation 'Doctrine\\DBAL\\Platforms\\AbstractPlatform::getSequenceNextValSQL' is not supported by platform.",
    "code": 0,
    "file": "/app/vendor/doctrine/dbal/src/Exception.php:22",
    "trace": [
        "/app/vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:3226",
        "/app/vendor/doctrine/orm/lib/Doctrine/ORM/Id/SequenceGenerator.php:59",  <--- oopsie
        "/app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:990",
        "/app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1816",
        "/app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1773",
        "/app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:660",
        "/app/var/cache/prod/ContainerADX73QW/EntityManager_9a5be93.php:120",
...
        "/app/vendor/symfony/http-kernel/HttpKernel.php:152",
        "/app/vendor/symfony/http-kernel/HttpKernel.php:74",
        "/app/vendor/symfony/http-kernel/Kernel.php:202",
        "/app/public/index.php:20"
    ]
}
```

That post helped me understand the stack trace: https://stackoverflow.com/a/14029064/334493  
Relevant docs: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#identifiers-primary-keys

**Comment by pok-git** [comment]
_doctrine/orm 2.13.1 / server_version: '5.7'_

changing  `@ORM\GeneratedValue()` to `@ORM\GeneratedValue(strategy="IDENTITY")`
 fixed the error for me... i.e.:   
   
 ```
   /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
    private $id;
```

**Comment by leonboot** [comment]
I believe the `AUTO` value is a convenience value which automatically chooses the right strategy, depending on the database driver. It uses `IDENTITY` for MySQL-style database backends, and `SEQUENCE` for Postgres-style backends. This is the reason the `serverVersion` parameter exists for the `DATABASE_URL` variable. If not present, Symfony will probe the database connection, but this requires an active database connection when performing a `bin/console cache:clear`, for instance. This might be an issue in CI processes.

The error mentioned in the issue topic occurs when Doctrine thinks it's using a Postgres-style database, while actually it is likely a MySQL or MariaDB database (or any other database that should use the `IDENTITY` strategy). Even though I had the correct `serverVersion` configured in my application in production, this error still occurred. That's because the value is written into the Symfony cache, so if you warm up the cache in CI, whatever value `serverVersion` is set to at that point will be used and written into the cache. This will likely be a Postgres version. This will result in the error mentioned in the issue topic in production. A `bin/console cache:clear` will resolve it, but ideally you'll want to fix it in CI, by providing a more sensible `DATABASE_URL` with an appropriate serverVersion for your production environment when you warm up your cache.

I hope this helps anyone who runs into this issue, especially in a CI/CD scenario as described above.
