### ISSUE TITLE
New annotation driver and typed properties not mentioned in docs

### ISSUE THREAD

**Issue by fridde** [doctrine/doctrine2#8804]
According to [this announcement post](https://www.doctrine-project.org/2021/05/24/orm2.9.html) from May 24 by @beberlei we now can use the new annotation syntax introduced in PHP 8 and also we can use typed properties to type hint associations between entities.

If I haven't missed anything, the docs make absolutely no mention of these features and only instruct the corresponding topics the "old way" (docblocks, yaml, XML, PHP).

Is this part of the docs an ongoing project? Or are these features not mature enough to be introduced into the docs?

**Comment by greg0ire** [comment]
> If I haven't missed anything

You have missed this: https://github.com/doctrine/orm/blob/2.9.x/docs/en/reference/attributes-reference.rst, probably because that page exists but for some reason, isn't reference anywhere. Would you like to fix that? Looking for its legacy counterpart shows where it should be referenced: https://github.com/doctrine/orm/search?q=annotations-reference

**Comment by fridde** [comment]
Done. Thanks for your help! You can close this issue as soon as the PR is approved.
