### ISSUE TITLE
wrapInTransaction missing from EntityManagerInterface

### ISSUE THREAD

**Issue by acelaya** [doctrine/doctrine2#9148]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.2

#### Summary

I have noticed the `transactional` method has been deprecated in v2.10, and it tells you to use `wrapInTransaction` instead.

However, regardless of the fact that this method is implemented in the `EntityManager` class, it is commented out in `EntityManagerInterface`.

![image](https://user-images.githubusercontent.com/2719332/138553168-15dc79a2-4676-4434-aeda-ad0594037c04.png)

Is this intended, or is it a mistake?

#### Current behavior

If I typehint to `EntityManagerInterface`, I cannot call `wrapeInTransaction`, as it does not exist in the interface, and `transactional` is marked as deprecated.

#### How to reproduce

N/A

#### Expected behavior

The method `wrapeInTransaction` is defined both in the interface and the implementation of the EntityManager.

**Comment by acelaya** [comment]
Ok, my mistake. I was apparently looking at v2.10.1 code (the IDE didn't update the opened tabs after `composer update`), while this has been fixed in v2.10.2

**Comment by Feolius** [comment]
Why was this issue closed? In 2.10.2 this method is still commented. And even though it is declared in the interface annotation, it creates some problems in PhpUnit tests refactoring still. You cannot simply rename "transactional" method in EntityMangerInterface mocks that were created via createMock() method, because this method "officially" doesn't exist. 

So, it's better to uncomment this line.

**Comment by greg0ire** [comment]
@Feolius that would be a BC-break for any class implementing the interface.
