### ISSUE TITLE
Support CHECK constraints

### ISSUE THREAD

**Issue by oojacoboo** [doctrine/doctrine2#9465]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

MySQL 8 introduced `CHECK` constraints a few years ago, something that's been around with various other RDBMS for many more years.  MySQL 8 support is now available across all major cloud providers and, as stated, has been available for a few years now.

You can read more about check constraints if you don't know about them, here:
https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html

Check constraints are a big deal and are very useful in validating the data being put into your database.  Here are a couple examples:

```SQL
ALTER TABLE `user` ADD CONSTRAINT `user.min_username_length` CHECK (LENGTH(`username`) >= 3);
```

Here you can see a username's length being forced to be at least 3 characters in length

```SQL
ALTER TABLE `user` ADD CONSTRAINT `user.email_validation` CHECK (`email` REGEXP "^[a-zA-Z0-9][a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]*?[a-zA-Z0-9._-]?@[a-zA-Z0-9][a-zA-Z0-9._-]*?[a-zA-Z0-9]?\\.[a-zA-Z]{2,63}$");
```

This will validate that an email address matches the regex for a valid email address

--

Now, I'm expecting that there are going to be some arguments that this type of validation can/should be placed into your application logic.  This is flawed thinking.  You cannot predict what other applications, scripts, or manual database execution is going to happen.  A database should maintain its data integrity and not rely on any other layers for this.  Bad data within a database can surface many issues and only compound problems.  Ensuring that your database only has data that fits with your domain makes application logic simpler and prevents associated errors from propagating.

**Comment by derrabus** [comment]
Since we don't want to build a MySQL island here:

* https://www.postgresql.org/docs/14/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS
* https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-check-constraints
* https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/constraint.html#GUID-1055EA97-BA6F-4764-A15F-1024FD5B6DFE__GUID-3D961DC5-3C55-4598-9AB6-A41BA7B90105
* https://mariadb.com/kb/en/constraint/#check-constraints

How would you imagine this support to look like? What would the ORM do with those constraints?

**Comment by oojacoboo** [comment]
> Since we don't want to build a MySQL island here:

Absolutely.  I didn't mean for this to be MySQL specific.  We use MySQL, obviously, and I'm not sure all of the supported RDBMS systems for Doctrine.  But, as you've listed, support is broad at this point.

Personally, we don't rely on Doctrine to update our database.  However, I'm sure many people do.  A check constraint would be treated almost exactly like a `uniqueConstraint` on the `Table` attribute definition.

```php
#[ORM\Table(
    name: 'user',
    uniqueConstraints: [...],
    checkConstraints: [
        new ORM\CheckConstraint(
            name: 'user.email_validation',
            check: [
                [engine: ORM\CheckConstraint::MYSQL, value: 'LENGTH(`username`) >= 3'],
            ],
        ),
    ],
)]
```

I realize you'd probably need to support RDBMS specific definitions here.  It wouldn't be worth trying to create a dictionary and maintaining an API or DSL for multi-engine support.

**Comment by derrabus** [comment]
I'm not sold on the `engine: mysql` part. If we implement that feature, it should be as vendor-agnostic as possible. Do you think, we can find a subset of check constraints with broad vendor support to start with?

Also, we probably need to teach DBAL's schema management to handle those constraints. cc @morozov

**Comment by morozov** [comment]
While checks as such are an important feature, implementing them in the DBAL seems to be a slippery slope to me.

The problem is that a check may include an arbitrary expression which are not standardized across the platforms. We do have an abstraction for building portable expressions but it's available as a runtime API while the schema definition is static (e.g. expressed in YAML).

Even if we agreed on accepting more or less standard expressions in checks, we'd face the problems like https://github.com/doctrine/dbal/pull/5234 since there's no reliable way to compare the expression from the schema definition and the one deployed to the database.

The DBAL already has some technical debt related to the default expressions (e.g. `ts NOT NULL DEFAULT CURRENT_TIMESTAMP`) where even primitive expressions in DDL need special handling.

Handling such expressions in the DBAL would require an introduction of an SQL parser that could parse both the "standard" expression from the schema definition (e.g. `LENGTH(username) >= 3`), parse its representation according to the SQL dialect of all supported platforms (e.g. `LEN([username]) >= 3` on SQL Server or `LENGTH("USERNAME") >= 3)` on Oracle and then cast them to some generic AST for comparison.

**Comment by derrabus** [comment]
Thank you for your input on this, @morozov! That sounds challanging indeed.

For the declaration on the ORM side, we could probably leverage DQL for declaring portable expressions. Translating those to the currently used SQL dialect should be straightforward, but the hard part would indeed be detecting a change in the constraint declaration.

@oojacoboo Do you want to work on that feature?

**Comment by oojacoboo** [comment]
@derrabus unfortunately I don't have a lot of capacity at the moment.  We also don't use Doctrine to update our schema.  I created this ticket because people need to be aware of and start using check constraints more, from a db design perspective.  

If DQL can be leveraged to provide unrestricted support, that sounds like the way to go.  However, the moment this restricts the ability to create a check constraint for your RDBMS, it's a case of  the tool getting in the way.  Obviously an abstracted implementation is the way to go from an API and syntax perspective.  But it should not be limiting.

**Comment by Aweptimum** [comment]
On comparing the definitions, it might be worth looking into what's available in each vendor's internal schemas. 

Postgres, for example, stores constraint definitions in [pg_constraint ](https://www.postgresql.org/docs/11/catalog-pg-constraint.html) that can be retrieved in a human-readable manner with [pg_get_constraintdef](https://dba.stackexchange.com/a/206609/234694). It includes pkeys, fkeys, and checks.

MySQL has a CHECK_CLAUSE in [information_schema.check_constraints](https://dev.mysql.com/doc/refman/8.0/en/information-schema-check-constraints-table.html) that stores the plain-text expression.

Not every vendor appears to do this. At least, I couldn't find out if SQLite does store check expressions from my 15 minutes of googling.

Either way, at some point it might be possible for Doctrine to compare the evaluated DQL against the db's stored expression during a diff and migrate the check if they're not strictly equal.

I'm not familiar enough with the innerworkings of doctrine enough to work on this, but I think each platform would need a `getCheckConstraintDefinition` method that queries each vendor's information schema for check expressions given a schema, table, column, and constraint name.

**Comment by beberlei** [comment]
@Aweptimum i wouldnt expect problems finding out the check expressions for each dbms, the problems @morozov mentioned come after that.

As @oojacoboo says they dont use the ORM for creating db schema, i believe this feature request to be from a POV of what dbms capabilities exist that the ORM not yet manages, instead of a real need. As such its better to not support this, to avoid building something that isnt fit for use or needed.

**Comment by goulashsoup** [comment]
@beberlei Maybe the `Table` attribute/annotation could get a `userOptions` property that can be set so that it is possible to add this functionality via extension?

**Comment by MaximeLaurenty** [comment]
@beberlei: we use the ORM for db schema, and we have DB constraints. For now they are poorly managed (ie: not managed), but we'd like to manage it properly. Is there any chance this will be implemented or do we need to implement our own system for constraints ?

**Comment by derrabus** [comment]
Nobody's working on this feature, if that answers your question.
